## **Задача:** 
Создать ноутбук, в котором будут приведены собственные примеры решения систем линейных уравнений матричным методом и методом Крамера.

# Матричным метод

Пусть дана система $n$ линейных уравнений с $n$ переменными $(n \times n)$.<br> Если основная матрица не вырождена, т.е. $\vert A \vert \ne 0$, тогда для матрицы $А$ существует $А^{-1}$. Умножив матричное уравнение на $А^{-1}$ получим: $$X = А^{-1} * B$$

Создадим и заполним матрицу:

In [23]:
import numpy as np
np.random.seed(0)
slau = np.random.randint(0, 15, size = (3, 4))
slau

array([[12,  5,  0,  3],
       [11,  3,  7,  9],
       [ 3,  5,  2,  4]])

Решим полученную систему уравнений 
$$
\begin{cases}
12x_{1} + 5x_{2} = 3 \\
11x_{1} + 3x_{2} + 7x_{3} = 9 \\
3x_{1} + 5x_{2} + 2x_{3} = 4
\end{cases}
$$

Приведем к матричному виду:

In [11]:
slau_a = slau[:, 0:3]
slau_b = slau[:, 3]
x = np.ones((3, 1))

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[12  5  0]
 [11  3  7]
 [ 3  5  2]]
slau_b
[3 9 4]


$$
\bar{A} = 
\left\lgroup\begin{matrix}
12 & 5 & 0 & \vert & 3 \cr
11 & 3 & 7 & \vert & 9 \cr
3 & 5 & 2 & \vert & 4
\end{matrix}\right\rgroup
$$

Найдем определитель $\vert A \vert$, обратную матрицу $А^{-1} = E / A$ и присоединенную $A^*$.Также найдем решения СЛАУ

In [17]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем обратную и присоединенную матрицу
    A_inv = np.linalg.inv(slau_a)
    x = A_inv.dot(slau_b)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[0.10481586 0.34844193 0.97167139]


# Метод Крамера

Рассмотрим систему из $n$ уравнений с $n$ неизвестными.<br> Если $\triangle \ne 0$, то система имеет единственное решение, которое может быть определенне по формулам Крамера $x_1 = \frac{\triangle_1}{\triangle};  x_2 = \frac{\triangle_2}{\triangle}; x_3 = \frac{\triangle_3}{\triangle}$ 

Создадим и заполним матрицу:

In [18]:
np.random.seed(0)
slau = np.random.randint(0, 15, size = (3, 4))
slau

array([[12,  5,  0,  3],
       [11,  3,  7,  9],
       [ 3,  5,  2,  4]])

Приведем к матричному виду:

In [19]:
slau_a = slau[:, 0:3]
slau_b = np.ones((3, 1))
x = np.ones((3, 1))
slau_b[0, 0] = slau[0, 3]
slau_b[1, 0] = slau[1, 3]
slau_b[2, 0] = slau[2, 3]

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[12  5  0]
 [11  3  7]
 [ 3  5  2]]
slau_b
[[3.]
 [9.]
 [4.]]


Найдем определитель и дополнительные определители, а текже решения по формулам Крамера

In [20]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем дополнительные определители
    for i in range(3):
        A_dop = slau_a.copy()
        A_dop[:, i] = slau_b[:, 0]
        x[i,0] = round(np.linalg.det(A_dop), 3) / round(np.linalg.det(slau_a), 3)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[[0.10481586]
 [0.34844193]
 [0.97167139]]
