## **Задача:** 
Создать ноутбук, в котором будут приведены собственные примеры на языке Python для каждого из представленных свойств матричных вычислений.

In [83]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [4]:
A = np.matrix('8 9 3 5; 0 9 5 17; 8 4 0 0')
print(A)
print("Транспонированная: ")
print(A.T)
print("Транспонированная второй раз: ")
R = (A.T).T
print(R)

[[ 8  9  3  5]
 [ 0  9  5 17]
 [ 8  4  0  0]]
Транспонированная: 
[[ 8  0  8]
 [ 9  9  4]
 [ 3  5  0]
 [ 5 17  0]]
Транспонированная второй раз: 
[[ 8  9  3  5]
 [ 0  9  5 17]
 [ 8  4  0  0]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [8]:
A = np.matrix('14 3; 7 8; 0 9')
B = np.matrix('1 9; 10 5; 12 7')
print(f"A:\n{A},\nB:\n{B}")

print("Транспонирование суммы матриц:")
L = (A + B).T
print(L)

print("Сумма транспонированных матриц:")
R = A.T + B.T
print(R)

A:
[[14  3]
 [ 7  8]
 [ 0  9]],
B:
[[ 1  9]
 [10  5]
 [12  7]]
Транспонирование суммы матриц:
[[15 17 12]
 [12 13 16]]
Сумма транспонированных матриц:
[[15 17 12]
 [12 13 16]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке

In [11]:
A = np.matrix('0 2; 1 9; 9 2')
B = np.matrix('23 4 6; 7 1 1')
print(f"A:\n{A},\nB:\n{B}")

print("Транспонирование произведения матриц:")
L = (A.dot(B)).T
print(L)

print("Произведение транспонированных матриц:")
R = (B.T).dot(A.T)
print(R)

A:
[[0 2]
 [1 9]
 [9 2]],
B:
[[23  4  6]
 [ 7  1  1]]
Транспонирование произведения матриц:
[[ 14  86 221]
 [  2  13  38]
 [  2  15  56]]
Произведение транспонированных матриц:
[[ 14  86 221]
 [  2  13  38]
 [  2  15  56]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу

In [12]:
A = np.matrix('23 4 6; 7 1 1')
k = 3
print(f"A:\n{A},\nk:{k}")

print("Транспонирование произведения матрицы на число:")
L =  (k * A).T
print(L)

print("Произведение числа на транспонированную матрицу:")
R =  k * (A.T)
print(R)

A:
[[23  4  6]
 [ 7  1  1]],
k:3
Транспонирование произведения матрицы на число:
[[69 21]
 [12  3]
 [18  3]]
Произведение числа на транспонированную матрицу:
[[69 21]
 [12  3]
 [18  3]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [17]:
A = np.matrix('1 0 9; 10 6 5; 12 1 7')
print(f"A:\n{A}")

print("\nОпределитель исходной матрицы:")
A_det = np.linalg.det(A)
print(format(A_det, '.9g'))

print("Определитель транспонированной матрицы:")
A_T_det = np.linalg.det(A.T)
print(format(A_T_det, '.9g'))

A:
[[ 1  0  9]
 [10  6  5]
 [12  1  7]]

Определитель исходной матрицы:
-521
Определитель транспонированной матрицы:
-521


_Действия над матрицами_

Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [19]:
A = np.matrix('1 2; 3 4')
print(f"A:\n{A}")

print("\nПроизведение единицы и матрицы:")
L = 1 * A
print(L)

A:
[[1 2]
 [3 4]]

Произведение единицы и матрицы:
[[1 2]
 [3 4]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [21]:
A = np.matrix('14 3; 7 8; 0 9')
Z = np.matrix('0 0; 0 0; 0 0')
L = 0 * A
print("Нулевая матрица:")
print(Z)
print("Произведение матрицы на 0:")
print(L)

Нулевая матрица:
[[0 0]
 [0 0]
 [0 0]]
Произведение матрицы на 0:
[[0 0]
 [0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [22]:
A = np.matrix('23 4 6; 7 1 1')
print(f"A:\n{A}")
print("\nПроизведение матрицы на сумму чисел:")
L = (6 + 2) * A
print(L)
print("Произведений матрицы на каждое из этих чисел:")
R = 6 * A + 2 * A
print(R)

A:
[[23  4  6]
 [ 7  1  1]]

Произведение матрицы на сумму чисел:
[[184  32  48]
 [ 56   8   8]]
Произведений матрицы на каждое из этих чисел:
[[184  32  48]
 [ 56   8   8]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [23]:
A = np.matrix('8 1 5; 7 7 1; 0 9 18')
print(f"A:\n{A}")
print("\nПроизведение матрицы на произведение чисел:")
L = (7 * 2) * A
print(L)

print("Произведений второго числа и заданной матрицы, умноженному на первое число:")
R = 7 * (2 * A)
print(R)

A:
[[ 8  1  5]
 [ 7  7  1]
 [ 0  9 18]]

Произведение матрицы на произведение чисел:
[[112  14  70]
 [ 98  98  14]
 [  0 126 252]]
Произведений второго числа и заданной матрицы, умноженному на первое число:
[[112  14  70]
 [ 98  98  14]
 [  0 126 252]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [25]:
A = np.matrix('0 9; 3 5')
B = np.matrix('1 8; 11 3')
k = 3
print(f"A:\n{A},\nB:\n{B}")

print("\nПроизведение суммы матриц на число:")
L = k * (A + B)
print(L)

print("\nCуммa произведений этих матриц на заданное число:")
R = k * A + k * B
print(R)

A:
[[0 9]
 [3 5]],
B:
[[ 1  8]
 [11  3]]

Произведение суммы матриц на число:
[[ 3 51]
 [42 24]]

Cуммa произведений этих матриц на заданное число:
[[ 3 51]
 [42 24]]


Сложение матриц

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [26]:
A = np.matrix('14 3; 7 8; 0 9')
B = np.matrix('1 9; 10 5; 12 7')
print(f"A:\n{A},\nB:\n{B}")

print("\nA + B")
L = A + B
print(L)
print("\nB + A")
R = B + A
print(R)

A:
[[14  3]
 [ 7  8]
 [ 0  9]],
B:
[[ 1  9]
 [10  5]
 [12  7]]

A + B
[[15 12]
 [17 13]
 [12 16]]

B + A
[[15 12]
 [17 13]
 [12 16]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от
порядка, в котором эта операция будет выполняться:

In [30]:
A = np.matrix('0 2 1; 9 9 2')
B = np.matrix('23 4 6; 7 1 1')
C = np.matrix('9 1 7; 9 6 3')
print(f"A:\n{A},\nB:\n{B},\nC:\n{C}")

print("\nA + (B + C)")
L = A + (B + C)
print(L)
print("\n(A + B) + C")
R = (A + B) + C
print(R)

A:
[[0 2 1]
 [9 9 2]],
B:
[[23  4  6]
 [ 7  1  1]],
C:
[[9 1 7]
 [9 6 3]]

A + (B + C)
[[32  7 14]
 [25 16  6]]

(A + B) + C
[[32  7 14]
 [25 16  6]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является
нулевой матрицей:

In [32]:
A = np.matrix('9 4 3; 2 3 3; 9 0 1')

print(f"A:\n{A}")
print(f"-A:\n{A * (-1)}")

print(f"Сумма:")
L = A + (-1)*A
print(L)

A:
[[9 4 3]
 [2 3 3]
 [9 0 1]]
-A:
[[-9 -4 -3]
 [-2 -3 -3]
 [-9  0 -1]]
Сумма:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [35]:
A = np.matrix('4 7; 1 2')
B = np.matrix('1 1; 9 3')
C = np.matrix('6 1; 2 0')
print(f"A:\n{A},\nB:\n{B},\nC:\n{C}")

print("A*(B*C)")
L = A.dot(B.dot(C))
print(L)
print("(A*B)*C")
R = (A.dot(B)).dot(C)
print(R)

A:
[[4 7]
 [1 2]],
B:
[[1 1]
 [9 3]],
C:
[[6 1]
 [2 0]]
A*(B*C)
[[452  67]
 [128  19]]
(A*B)*C
[[452  67]
 [128  19]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [36]:
A = np.matrix('0 2 1; 9 9 2; 5 6 1')
B = np.matrix('23 4 6; 7 1 1; 2 0 8')
C = np.matrix('9 1 7; 9 6 3; 5 6 1')
print(f"A:\n{A},\nB:\n{B},\nC:\n{C}")

print("A * (B+C)")
L = A.dot(B + C)
print(L)
print("A*B + A*C)")
R = A.dot(B) + A.dot(C)
print(R)

A:
[[0 2 1]
 [9 9 2]
 [5 6 1]],
B:
[[23  4  6]
 [ 7  1  1]
 [ 2  0  8]],
C:
[[9 1 7]
 [9 6 3]
 [5 6 1]]
A * (B+C)
[[ 39  20  17]
 [446 120 171]
 [263  73  98]]
A*B + A*C)
[[ 39  20  17]
 [446 120 171]
 [263  73  98]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [40]:
A = np.matrix('0 9; 3 5')
B = np.matrix('1 8; 11 3')
print(f"A:\n{A},\nB:\n{B}\n")
      
print("A*B")
L = A.dot(B)
print(L)
print("B*A")
R = B.dot(A)
print(R)

A:
[[0 9]
 [3 5]],
B:
[[ 1  8]
 [11  3]]

A*B
[[99 27]
 [58 39]]
B*A
[[ 24  49]
 [  9 114]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [41]:
A = np.matrix('0 2 1; 9 9 2; 5 6 1')
E = np.eye(3)
print(f"A:\n{A}")

print("E*A")
L = E.dot(A)
print(L)
print("A*E")
R = A.dot(E)
print(R)

A:
[[0 2 1]
 [9 9 2]
 [5 6 1]]
E*A
[[0. 2. 1.]
 [9. 9. 2.]
 [5. 6. 1.]]
A*E
[[0. 2. 1.]
 [9. 9. 2.]
 [5. 6. 1.]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [42]:
A = np.matrix('0 2 1; 9 9 2; 5 6 1')
E = np.zeros((3, 3))
print(f"A:\n{A}")

print("Z*A")
L = Z.dot(A)
print(L)
print("A*Z")
R = A.dot(Z)
print(R)

A:
[[0 2 1]
 [9 9 2]
 [5 6 1]]
Z*A
[[0 0 0]
 [0 0 0]
 [0 0 0]]
A*Z
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [47]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

print(f"A(T):\n{A.T}\n")
det_A_t = round(np.linalg.det(A.T), 3)
print(f"|A(T)| = {det_A_t}")


A:
[[9 1 7]
 [9 6 3]
 [5 6 1]]

|A| = 66.0

A(T):
[[9 9 5]
 [1 6 6]
 [7 3 1]]

|A(T)| = 66.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [53]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

A = np.matrix('0 1 7; 0 6 3; 0 6 1')
print(f"A:\n{A}\n")

det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

A = np.matrix('9 1 7; 9 6 3;0 0 0')
print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

A:
[[9 1 7]
 [9 6 3]
 [5 6 1]]

|A| = 66.0

A:
[[0 1 7]
 [0 6 3]
 [0 6 1]]

|A| = 0.0

A:
[[9 1 7]
 [9 6 3]
 [0 0 0]]

|A| = 0.0



Свойство 3. При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [58]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

B = np.matrix('9 1 7; 5 6 1; 9 6 3')
print(f"B:\n{B}\n")
det_B = round(np.linalg.det(B), 3)
print(f"|B| = {det_B}\n")

A:
[[9 1 7]
 [9 6 3]
 [5 6 1]]

|A| = 66.0

B:
[[9 1 7]
 [5 6 1]
 [9 6 3]]

|B| = -66.0



Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [59]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

A = np.matrix('9 1 7; 5 6 1; 5 6 1')
print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}\n")

A:
[[9 1 7]
 [9 6 3]
 [5 6 1]]

|A| = 66.0

A:
[[9 1 7]
 [5 6 1]
 [5 6 1]]

|A| = 0.0



Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [67]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')

k = 3

print(f"A:\n{A}\n")
det_A = round(np.linalg.det(A), 3)
print(f"|A| = {det_A}")
print(f"|A| * k = {det_A * k}\n")

B = A.copy()
B[2, :] = k * B[2, :]
print(f"B:\n{B}\n")

det_B = round(np.linalg.det(B), 3)
print(f"|B| = {det_B}\n")


A:
[[9 1 7]
 [9 6 3]
 [5 6 1]]

|A| = 66.0
|A| * k = 198.0

B:
[[ 9  1  7]
 [ 9  6  3]
 [15 18  3]]

|B| = 198.0



Свойство 6. Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [71]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print("C")
print(C)
print("A")
print(A)
print("B")
print(B)
print("|C|")
print(round(np.linalg.det(C), 3))
print("|A| + |B|")
print(round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3))

C
[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
A
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
B
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]
|C|
4.0
|A| + |B|
4.0


Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:


In [74]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
k = 3

B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]

print("A")
print(A)
print("B")
print(B)

print("\n|A|")
print(round(np.linalg.det(A), 3))
print("|B|")
print(round(np.linalg.det(B), 3))

A
[[9 1 7]
 [9 6 3]
 [5 6 1]]
B
[[ 9  1  7]
 [36  9 24]
 [ 5  6  1]]

|A|
66.0
|B|
66.0


Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю

In [75]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print("A")
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
print("\n|A|")
print(round(np.linalg.det(A), 3))

A
[[9 1 7]
 [9 6 3]
 [5 6 1]]

|A|
0.0


Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [78]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print("A")
print(A)
print(round(np.linalg.det(A), 3))

k = 4
A[1, :] = k * A[0, :]
print("\nnew A")
print(A)
print(round(np.linalg.det(A), 3))

A
[[9 1 7]
 [9 6 3]
 [5 6 1]]
66.0

new A
[[ 9  1  7]
 [36  4 28]
 [ 5  6  1]]
0.0


Обратная матрица

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [80]:
A = np.matrix('4 6; 7 1')
print("A")
print(A)
A_inv = np.linalg.inv(A)
print("A_inv")
print(A_inv)
A_inv_inv = np.linalg.inv(A_inv)
print("A_inv_inv")
print(A_inv_inv)

A
[[4 6]
 [7 1]]
A_inv
[[-0.02631579  0.15789474]
 [ 0.18421053 -0.10526316]]
A_inv_inv
[[4. 6.]
 [7. 1.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [81]:
A = np.matrix('4 6; 7 1')

print("Обратная матрица транспонированной матрицы:")
L = np.linalg.inv(A.T)
print(L)

print("Транспонированная матрица от обратной матрицы:")
R = (np.linalg.inv(A)).T
print(R)

Обратная матрица транспонированной матрицы:
[[-0.02631579  0.18421053]
 [ 0.15789474 -0.10526316]]
Транспонированная матрица от обратной матрицы:
[[-0.02631579  0.18421053]
 [ 0.15789474 -0.10526316]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [82]:
A = np.matrix('4 6; 7 1')
B = np.matrix('1 9; 8 2')

print("Обратная матрица произведения матриц:")
L = np.linalg.inv(A.dot(B))
print(L)

print("Произведение обратных матриц:")
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(R)


Обратная матрица произведения матриц:
[[ 0.02443609 -0.01804511]
 [-0.0056391   0.01954887]]
Произведение обратных матриц:
[[ 0.02443609 -0.01804511]
 [-0.0056391   0.01954887]]
