Создать ноутбук, в котором будут приведены собственные примеры решения систем линейных уравнений матричным методом и методом Крамера.

# Матричным метод

In [56]:
import numpy as np
slau = np.random.randint(0, 15, size = (3, 4))
slau

array([[ 7, 14,  4,  8],
       [ 1,  0,  5,  6],
       [ 7,  3, 10,  5]])

In [62]:
slau_a = slau[:, 0:3]
slau_b = slau[:, 3]
x = np.ones((3, 1))

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[ 7 14  4]
 [ 1  0  5]
 [ 7  3 10]]
slau_b
[8 6 5]


In [63]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем обратную матрицу
    A_inv = np.linalg.inv(slau_a)
    x = A_inv.dot(slau_b)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[-2.09338521  1.15564202  1.61867704]


# Метод Крамера

In [46]:
slau = np.random.randint(0, 15, size = (3, 4))

In [60]:
slau_a = slau[:, 0:3]
slau_b = np.ones((3, 1))
x = np.ones((3, 1))
slau_b[0, 0] = slau[0, 3]
slau_b[1, 0] = slau[1, 3]
slau_b[2, 0] = slau[2, 3]

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[ 7 14  4]
 [ 1  0  5]
 [ 7  3 10]]
slau_b
[[8.]
 [6.]
 [5.]]


In [61]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем дополнительные определители
    for i in range(3):
        A_dop = slau_a.copy()
        A_dop[:, i] = slau_b[:, 0]
        x[i,0] = round(np.linalg.det(A_dop), 3) / round(np.linalg.det(slau_a), 3)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[[-2.09338521]
 [ 1.15564202]
 [ 1.61867704]]
