Создать ноутбук, в котором будут приведены собственные примеры решения систем линейных уравнений матричным методом и методом Крамера.

# Матричным метод

In [3]:
import numpy as np
slau = np.random.randint(0, 15, size = (3, 4))
slau

array([[ 8, 10,  5, 14],
       [11, 14,  5,  7],
       [ 3,  7,  2,  1]])

In [41]:
slau_a = slau[:, 0:3]
slau_b = np.ones((3, 1))
x = np.ones((3, 1))
slau_b[0, 0] = slau[0, 3]
slau_b[1, 0] = slau[1, 3]
slau_b[2, 0] = slau[2, 3]

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[ 8 10  5]
 [11 14  5]
 [ 3  7  2]]
slau_b
[[14.]
 [ 7.]
 [ 1.]]


In [42]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем обратную матрицу
    A_inv = np.linalg.inv(slau_a)
    x = A_inv.dot(slau_b)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[[-0.26530612]
 [-1.55102041]
 [ 6.32653061]]


# Метод Крамера

In [46]:
slau = np.random.randint(0, 15, size = (3, 4))

In [47]:
slau_a = slau[:, 0:3]
slau_b = np.ones((3, 1))
x = np.ones((3, 1))
slau_b[0, 0] = slau[0, 3]
slau_b[1, 0] = slau[1, 3]
slau_b[2, 0] = slau[2, 3]

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[ 2  7  3]
 [13 11  0]
 [ 9 14  2]]
slau_b
[[6.]
 [1.]
 [3.]]


In [52]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем дополнительные определители
    for i in range(3):
        A_dop = slau_a.copy()
        A_dop[:, i] = slau_b[:, 0]
        x[i,0] = round(np.linalg.det(A_dop), 3) / round(np.linalg.det(slau_a), 3)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[[ 0.54954955]
 [-0.55855856]
 [ 2.93693694]]
