## **Задача:** 
Создать ноутбук, в котором будут приведены собственные примеры решения систем линейных уравнений матричным методом и методом Крамера.

# Матричным метод

Пусть дана система $n$ линейных уравнений с $n$ переменными $(n \times n)$.<br> Если основная матрица не вырождена, т.е. $\vert A \vert \ne 0$, тогда для матрицы $А$ существует $А^{-1}$. Умножив матричное уравнение на $А^{-1}$ получим: $$X = А^{-1} * B$$

Создадим и заполним матрицу:

In [56]:
import numpy as np
slau = np.random.randint(0, 15, size = (3, 4))
slau

array([[ 7, 14,  4,  8],
       [ 1,  0,  5,  6],
       [ 7,  3, 10,  5]])

Решим полученную систему уравнений 
$$
\begin{cases}
7x_{1} + 14x_{2} + 4x_{3} = 8 \\
x_{1} + 5x_{3} = 6 \\
7x_{1} + 3x_{2} + 10x_{3} = 5
\end{cases}
$$

Приведем к матричному виду:

In [62]:
slau_a = slau[:, 0:3]
slau_b = slau[:, 3]
x = np.ones((3, 1))

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[ 7 14  4]
 [ 1  0  5]
 [ 7  3 10]]
slau_b
[8 6 5]


$$
\bar{A} = 
\left\lgroup\begin{matrix}
7 & 14 & 4 & \vert & 8 \cr
1 & 0 & 5 & \vert & 6 \cr
7 & 3 & 10 & \vert & 5
\end{matrix}\right\rgroup
$$

Найдем определитель $\vert A \vert$, обратную матрицу $А^{-1} = E / A$ и присоединенную $A^*$.Также найдем решения СЛАУ

In [63]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем обратную и присоединенную матрицу
    A_inv = np.linalg.inv(slau_a)
    x = A_inv.dot(slau_b)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[-2.09338521  1.15564202  1.61867704]


# Метод Крамера

Рассмотрим систему из $n$ уравнений с $n$ неизвестными.<br> Если $\triangle \ne 0$, то система имеет единственное решение, которое может быть определенне по формулам Крамера $x_1 = \frac{\triangle_1}{\triangle};  x_2 = \frac{\triangle_2}{\triangle}; x_3 = \frac{\triangle_3}{\triangle}$ 

Создадим и заполним матрицу:

In [46]:
slau = np.random.randint(0, 15, size = (3, 4))

Приведем к матричному виду:

In [60]:
slau_a = slau[:, 0:3]
slau_b = np.ones((3, 1))
x = np.ones((3, 1))
slau_b[0, 0] = slau[0, 3]
slau_b[1, 0] = slau[1, 3]
slau_b[2, 0] = slau[2, 3]

print("slau_a")
print(slau_a)
print("slau_b")
print(slau_b)

slau_a
[[ 7 14  4]
 [ 1  0  5]
 [ 7  3 10]]
slau_b
[[8.]
 [6.]
 [5.]]


Найдем определитель и дополнительные определители, а текже решения по формулам Крамера

In [61]:
#Найдем определитель
A_det = np.linalg.det(slau_a)

if A_det != 0:
    #Найдем дополнительные определители
    for i in range(3):
        A_dop = slau_a.copy()
        A_dop[:, i] = slau_b[:, 0]
        x[i,0] = round(np.linalg.det(A_dop), 3) / round(np.linalg.det(slau_a), 3)
    print("Решения:")
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить")

Решения:
[[-2.09338521]
 [ 1.15564202]
 [ 1.61867704]]
